[project]
name = "mobile-price-service"
version = "0.2.2"
description = "Homework"
requires-python= ">=3.11,<3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "pandas",
    "scikit-learn>=1.6,<1.7",
    "joblib",
    "psycopg[binary]"
]

[dependency-groups]
dev = [
    'pytest',
    'httpx2',
    "locust",
    'ruff',
]

[build-system]
requires = ['uv_build>=0.10, <0.11']
build-backend = 'uv_build'

[tool.uv.build-backend]
module-name = 'mobile_price'

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"

[tool.ruff]
line-length = 150

[tool.ruff.lint]
select = ["E", "F", "I", 'B', 'UP']