[project]
name = "mobile-price-service"
version = "0.0.2"
description = "Homework"
requires-python= ">=3.11,<3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "pandas",
    "scikit-learn",
    "joblib",
    "psycopg[binary]"
]

[dependecy-groups]
dev = [
    'pytest',
    'httpx',
    'locust',
    'ruff',
]

[build-system]
requires = ['uv_build>=0.10, <0.11']
build-backend = 'uv_build'

[tool.uv.build-backend]
module-name = 'mobile_price'

[tool.pytest.ini_options]
testpaths = ["tests"]
